version: '2'

services:
  microsoft.knowzy.webapp:
    image: microsoft.knowzy.webapp
    build:
      context: ./src/1. WebApp/Microsoft.Knowzy.WebApp
      dockerfile: Dockerfile

  microsoft.knowzy.ordersapi:
    image: microsoft.knowzy.ordersapi
    build:
      context: ./src/2. Services/APIs/Microsoft.Knowzy.OrdersAPI
      dockerfile: Dockerfile
